services:
  app:
    image: golang:1.25
    entrypoint: sh -c "go install github.com/air-verse/air@latest && go mod tidy && air"
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
